### ISSUE TITLE
Issue with Fast Startup enabled

### ISSUE THREAD

**Issue by ChrisRfr** [patrickgill/ntpwedit#1]
Hi,

There is a concern with the NTPWedit, if Fast Startup is enabled.
 Fast startup simply loads the hibernation file (Hiberfil.sys) into memory to restore the previously saved image.
 As a result, any changes you made from PE will be lost !. Also in some cases, editing NTFS while system is on hibernation state may result in system file corruption.

What do you think about a "small" addition:
 Search for Hiberfil.sys at the root of the host system drive and display a text on Interface (probably red, blinking) like:
 "Fast Startup detected, any changes will be lost. To disabled Fast startup (Hiberfil.sys), you can boot to Windows and restart (don't shtudown) from the log in screen"

Best Regards

**Comment by patrickgill** [comment]
Feel free to fork and change it
